version: 0.0
os: linux

files:
  - source: /
    destination: /home/deadlineuser/server
file_exists_behavior: OVERWRITE

permissions:
  - object: /
    pattern: "**"
    owner: deadlineuser
    group: deadlineuser

hooks:
  BeforeInstall:
    - location: scripts/install_log_agent
      timeout: 300
      runas: root
    # - location: install-packages-instance
    #   timeout: 300
    #   runas: deadlineuser
  ApplicationStart:
    - location: scripts/run_test # apply will create or destroy depending on the env vars present
      timeout: 3600 # 1 hour timeout.
      runas: deadlineuser
  # ApplicationStop:
  #   - location: deploy/destroy
  #     timeout: 3600 # 1 hour timeout.
  #     runas: deadlineuser
  # ApplicationStop:
  #   - location: scripts/stop
  #     timeout: 300
  #     runas: deadlineuser