#!/bin/bash

set -e

### All scripts require this
EXECDIR="$(pwd)"
SOURCE=${BASH_SOURCE[0]} # resolve the script dir even if a symlink is used to this script
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR=$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )
  SOURCE=$(readlink "$SOURCE")
  [[ $SOURCE != /* ]] && SOURCE=$DIR/$SOURCE # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
SCRIPTDIR=$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd ) # The directory of this script
###

. $SCRIPTDIR/zip # Zip and deploy app

# Create deployment
cd $SCRIPTDIR/..

aws deploy create-deployment \
  --application-name firehawk-codedeploy-test-app \
  --deployment-config-name CodeDeployDefault.OneAtATime \
  --deployment-group-name firehawk-test-group \
  --description "Firehawk test" \
  --s3-location bucket=codedeploy.dev.firehawkvfx.com,bundleType=zip,key=codedeploy-app-test-firehawk.zip \
  --file-exists-behavior OVERWRITE \
  --ignore-application-stop-failures

cd $EXECDIR