#!/bin/bash

set -e

cd $SCRIPTDIR/..

aws deploy create-deployment \
  --application-name firehawk-codedeploy-test-app \
  --deployment-config-name CodeDeployDefault.OneAtATime \
  --deployment-group-name firehawk-test-group \
  --description "Firehawk test" \
  --s3-location bucket=codedeploy.dev.firehawkvfx.com,bundleType=zip,key=codedeploy-app-test-firehawk.zip \
  --file-exists-behavior OVERWRITE \
  --ignore-application-stop-failures